### ISSUE TITLE
"path" error

### ISSUE THREAD

**Issue by priyal-firminiq** [seald/nedb#40] opened 2023-06-13 09:04 UTC
It is giving "path" module not found error while starting the react server.
it ot not getting the " module in node modules file.

**Comment by tex0l** [comment] 2023-06-13 09:12
Hi,
Could you please send a full repro case that I could `npm i && npm start` locally ?

**Comment by tex0l** [comment] 2024-01-11 15:40
I believe this is a duplicate of https://github.com/seald/nedb/issues/50, closing.

**Closed by tex0l** 2024-01-11 15:40 UTC
